### ISSUE TITLE
improve background of app !

### ISSUE THREAD

**Issue by sudipt1999** [NJACKWinterOfCode/FaceRecApp#4]
improve background of app !

**Comment by Mehulipal** [comment]
I am working on it.

**Comment by ankushbhardwxj** [comment]
@sudipt1999 I would like to get this done.

**Comment by sudipt1999** [comment]
sure go ahead!

**Comment by ankushbhardwxj** [comment]
@sudipt1999 I see that you've used `react-particle-js` for the background which is really cool. Do you want to get rid of it or should I improve on it ?

**Comment by sudipt1999** [comment]
As you wish !
