### ISSUE TITLE
improve ui of textinput

### ISSUE THREAD

**Issue by sudipt1999** [NJACKWinterOfCode/FaceRecApp#5]
improve ui of textinput where we are putting image url

**Comment by Mehulipal** [comment]
I want to work on it.Can I?

**Comment by sudipt1999** [comment]
sure

**Comment by ankushbhardwxj** [comment]
@sudipt1999 if anyone else is not assigned to this, please assign me. I can get this done.

**Comment by sudipt1999** [comment]
I guess @Mehulipal  is working on it ! please wait till this weekend if he doesn'e responds back I will assign you

**Comment by ankushbhardwxj** [comment]
@sudipt1999 I guess I can be assigned now ?

**Comment by sudipt1999** [comment]
yeah sure! go ahead!
