### ISSUE TITLE
Unable to run project

### ISSUE THREAD

**Issue by ankushbhardwxj** [NJACKWinterOfCode/FaceRecApp#6]
@sudipt1999  Tried running the project as described in README. Got the following errors !
![error1](https://user-images.githubusercontent.com/40923324/70344049-c6e40680-187e-11ea-84c6-2d87162779d9.PNG)
![error2](https://user-images.githubusercontent.com/40923324/70344093-dd8a5d80-187e-11ea-97dc-9a7c93e0a322.PNG)

**Comment by sudipt1999** [comment]
Kindly make sure you are connected to internet !!!
and follow this https://github.com/NJACKWinterOfCode/FaceRecApp/blob/master/README.md
 your problem I seem to have with internet connection only because its shows network error!
