### ISSUE TITLE
Add single command `npm run dev`

### ISSUE THREAD

**Issue by ankushbhardwxj** [NJACKWinterOfCode/FaceRecApp#8]
Currently we have to go to `face` and `faceApi` directory and have to do `npm start` to begin developement. This issue is for adding a single command `npm run dev` that can start both client and server at the same time.

**Comment by ankushbhardwxj** [comment]
@sudipt1999 I'm working on this.

**Comment by sudipt1999** [comment]
sure i find it legit!
